# Generated by Django 4.2.6 on 2023-10-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=50)),
                ('goods_description', models.CharField(max_length=255)),
                ('goods_quantity', models.CharField(max_length=50)),
                ('any_offer', models.CharField(max_length=150)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
