# Generated by Django 4.2.7 on 2024-09-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='service_charge_business_number',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyblock',
            name='rent_charge_business_number',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
