# Generated by Django 4.2.7 on 2024-09-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_service_charge_business_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='service_charge_business_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='propertyblock',
            name='rent_charge_business_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ServiceChargeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_months_paid', models.IntegerField()),
                ('total_months_unpaid', models.IntegerField()),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
            ],
        ),
    ]
