# Generated by Django 4.2.7 on 2024-02-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyblock_annual_service_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyblock',
            name='annual_service_charge',
        ),
    ]
