# Generated by Django 4.2.7 on 2024-09-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_service_charge_business_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicechargecollection',
            name='tenant',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicechargecollection',
            name='total_months_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicechargecollection',
            name='total_months_unpaid',
            field=models.IntegerField(null=True),
        ),
    ]
