# Generated by Django 4.2.7 on 2024-09-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_servicechargecollection_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyblock',
            name='annual_service_charge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyblock',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
