# Generated by Django 5.2.3 on 2026-05-04 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Activation fee amount', max_digits=10)),
                ('payment_mode', models.CharField(default='mpesa', help_text='Payment method (mpesa, card, etc.)', max_length=15)),
                ('status', models.IntegerField(default=0, help_text='0=pending, 1=completed, 2=failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(help_text='Landlord user who is paying activation fee', on_delete=django.db.models.deletion.CASCADE, related_name='activation_payment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activation Payment',
                'verbose_name_plural': 'Activation Payments',
                'db_table': 'activation_payments',
            },
        ),
        migrations.CreateModel(
            name='ActivationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, help_text='0=pending, 1=completed, 2=failed')),
                ('MerchantRequestID', models.CharField(blank=True, max_length=50, null=True)),
                ('CheckoutRequestID', models.CharField(blank=True, max_length=50, null=True)),
                ('MpesaReceiptNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('TransactionDate', models.CharField(blank=True, max_length=20, null=True)),
                ('platform_earnings', models.DecimalField(decimal_places=2, default=0, help_text='Full activation fee goes to platform', max_digits=10)),
                ('date_initiated', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('ResultCode', models.CharField(blank=True, max_length=10, null=True)),
                ('ResultDesc', models.TextField(blank=True, null=True)),
                ('activation_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='authentication.activationpayment')),
            ],
            options={
                'verbose_name': 'Activation Transaction',
                'verbose_name_plural': 'Activation Transactions',
                'db_table': 'activation_transactions',
                'ordering': ['-date_initiated'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlord_activation_fee', models.DecimalField(decimal_places=2, default=500.0, help_text='Amount in KES that landlords pay for account activation', max_digits=10)),
                ('platform_commission_rate', models.DecimalField(decimal_places=4, default=0.05, help_text='Platform commission rate (e.g., 0.05 for 5%)', max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
                'db_table': 'system_configuration',
            },
        ),
    ]
