# Generated by Django 5.2.3 on 2026-05-04 10:02

from django.db import migrations


def create_default_config(apps, schema_editor):
    """Create default system configuration"""
    SystemConfiguration = apps.get_model('authentication', 'SystemConfiguration')
    SystemConfiguration.objects.get_or_create(
        pk=1,
        defaults={
            'landlord_activation_fee': 500.00,
            'platform_commission_rate': 0.05,
        }
    )


def reverse_config(apps, schema_editor):
    """Remove default configuration"""
    SystemConfiguration = apps.get_model('authentication', 'SystemConfiguration')
    SystemConfiguration.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_activationpayment_activationtransaction_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_config, reverse_config),
    ]
