# Generated by Django 4.2.7 on 2024-02-09 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('payment_mode', models.CharField(choices=[('mpesa', 'mpesa'), ('card', 'card')], default='mpesa', max_length=15)),
                ('annual_service_charge', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.IntegerField(default=0)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('MerchantRequestID', models.CharField(max_length=50, null=True)),
                ('CheckoutRequestID', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'services',
                'db_table': 'services',
            },
        ),
    ]
