# Generated by Django 4.2.6 on 2024-01-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='annual_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
