# Generated by Django 4.2.7 on 2024-09-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_service_charge_business_number_and_more'),
        ('tenant_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
    ]
