# Generated by Django 4.2.7 on 2024-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_services', '0002_services_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='balance_service_charge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
