# Generated by Django 4.2.6 on 2024-01-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_services', '0002_services_annual_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='annual_amount',
        ),
    ]
