# Generated by Django 4.2.6 on 2024-01-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_services', '0003_remove_services_annual_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='annual_service_charge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
