# Generated by Django 4.2.7 on 2024-09-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_services', '0003_services_balance_service_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='CheckoutRequestID',
        ),
        migrations.RemoveField(
            model_name='services',
            name='MerchantRequestID',
        ),
        migrations.RemoveField(
            model_name='services',
            name='date_paid',
        ),
        migrations.RemoveField(
            model_name='services',
            name='status',
        ),
        migrations.CreateModel(
            name='serviceTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('MerchantRequestID', models.CharField(max_length=50, null=True)),
                ('CheckoutRequestID', models.CharField(max_length=50, null=True)),
                ('service_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_services.services')),
            ],
            options={
                'verbose_name_plural': 'services_transactions',
                'db_table': 'services_transactions',
            },
        ),
    ]
