# Generated by Django 4.2.7 on 2024-09-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_services', '0004_remove_services_checkoutrequestid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='annual_service_charge',
        ),
    ]
