# Generated by Django 4.2.7 on 2024-04-22 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_services', '0004_services_annual_service_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='annual_service_charge',
            new_name='annual_balance_service_charge',
        ),
    ]
