# Generated by Django 4.2.7 on 2024-09-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_services', '0005_remove_services_annual_service_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetransactions',
            name='isB2CCompleted',
            field=models.IntegerField(default=0),
        ),
    ]
