# Generated by Django 4.2.7 on 2024-10-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_services', '0006_servicetransactions_isb2ccompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='balance_service_charge',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
    ]
