# Generated by Django 4.2.7 on 2024-12-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_services', '0007_alter_services_balance_service_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
