# Generated by Django 5.2.3 on 2026-05-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_services', '0008_services_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetransactions',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicetransactions',
            name='landlord_payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicetransactions',
            name='platform_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
