# Generated by Django 5.2.3 on 2026-05-03 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertyblock_annual_service_charge_and_more'),
        ('tenant_services', '0009_servicetransactions_commission_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('mpesa', 'mpesa'), ('card', 'card')], default='mpesa', max_length=15)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.propertyblock')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'rent_payments',
                'db_table': 'rent_payments',
                'unique_together': {('user', 'property_block', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='RentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('date_paid', models.DateField(auto_now_add=True)),
                ('MerchantRequestID', models.CharField(max_length=50, null=True)),
                ('CheckoutRequestID', models.CharField(max_length=50, null=True)),
                ('isB2CCompleted', models.IntegerField(default=0)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('landlord_payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_services.rentpayment')),
            ],
            options={
                'verbose_name_plural': 'rent_transactions',
                'db_table': 'rent_transactions',
            },
        ),
    ]
