# Generated by Django 4.2.7 on 2024-04-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
