# Generated by Django 5.2.3 on 2026-05-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_landlord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocklandlord',
            name='approver',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
